#!/usr/bin/env python3
"""One translation unit from the module sources, so the tool can be built
without itself.

A tool that turns modules into headers has to be built before it can turn
anything, and its own sources are modules. So the same transformation is done
here by hand -- the `export` keyword off, the module preamble replaced by
includes -- which is exactly what the tool does, minus the part only a compiler
can answer: the include list below is written out rather than discovered.

This is the bootstrap and nothing else. The real build is the CMake one, and
the check that this file stays honest is that both produce a tool that agrees
with itself.
"""
import pathlib
import sys

PREAMBLE = """module;

export module demodulizer;
import libtooling;
import std;
"""

INCLUDES = """// Generated by bootstrap/make_tu.py -- do not edit.
#include <clang/AST/ASTConsumer.h>
#include <clang/AST/ASTContext.h>
#include <clang/AST/RecursiveASTVisitor.h>
#include <clang/Basic/SourceManager.h>
#include <clang/Frontend/CompilerInstance.h>
#include <clang/Frontend/FrontendAction.h>
#include <clang/Lex/HeaderSearch.h>
#include <clang/Lex/PPCallbacks.h>
#include <clang/Lex/Preprocessor.h>
#include <clang/Rewrite/Core/Rewriter.h>
#include <clang/Tooling/CommonOptionsParser.h>
#include <clang/Tooling/Tooling.h>
#include <llvm/Support/CommandLine.h>
#include <llvm/Support/Path.h>
#include <llvm/Support/raw_ostream.h>
#include <cstdlib>
#include <map>
#include <memory>
#include <optional>
#include <set>
#include <string>
#include <string_view>
#include <system_error>
#include <vector>
"""


def unexported(text: str) -> str:
    return "\n".join(
        line[len("export ") :] if line.startswith("export ") else line
        for line in text.split("\n")
    )


def main() -> int:
    here = pathlib.Path(__file__).resolve().parent
    src = here.parent / "src"
    body = (src / "demodulizer.cc").read_text()
    if PREAMBLE not in body:
        print("the module preamble has moved; this script needs telling",
              file=sys.stderr)
        return 1
    body = body.replace(PREAMBLE, INCLUDES)
    entry = "\n".join(
        line for line in (src / "main.cc").read_text().split("\n")
        if not line.startswith("import ")
    )
    out = here / "demodulizer_all.cc"
    out.write_text(unexported(body + "\n" + entry))
    print(f"wrote {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
